### ISSUE TITLE
table styling

### ISSUE THREAD

**Issue by lizshalley** [web-illinois/toolkit#111]
See table styling in Zeplin:

https://zpl.io/V1xprQw
zpl://project?pid=608186933d2d341c92c71926

**Comment by mwllr** [comment]
- [ ] Use gray background color instead of the blueish one - Use #f4f4f4
- [ ] Only thing I see is that the rows of the table on mobile/responsive small version are still same height as if multilple lines would be showing, but they aren't. Anyway to get around this??

![Screen Shot 2021-07-20 at 11 47 19 AM](https://user-images.githubusercontent.com/54747669/126363758-91e16bcf-de90-4f74-8624-b209dd13e492.png)

**Comment by bryanjonker-illinois** [comment]
Changed color, added it to the CSS variable palette. 

Unfortunately, the spacing is a known issue with browsers. Hopefully, this will get fixed relatively soon.

**Comment by lauralhayden** [comment]
- Could you swap the border color for a lighter one (#d2d2d2)? I see the speck says #707070, but when I sample the color it is #d3d3d3. the il-cloud-3 seems to be the right one (#d2d2d2)

**Comment by mwllr** [comment]
https://cdn.brand.illinois.edu/toolkit/dev/examples/stylesheets/tables/index.html

Text: Sample information from Responsive Tables ---should be left aligned.
