### ISSUE TITLE
Footer - titles of lists 1-4

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#133]
Keith request to change the aria labels for the footer lists...Please tag Keith also.

<img width="1064" alt="Screen Shot 2021-07-13 at 2 51 57 PM" src="https://user-images.githubusercontent.com/54747669/125863463-419d290e-30f0-4edc-8656-334b453dc874.png">

**Comment by mwllr** [comment]
again - tag or email Keith for verification?

**Comment by bryanjonker-illinois** [comment]
@khays9 -- can you look at this? Thanks.

**Comment by khays9** [comment]
Modify the <nav> elements to use the aria-labelledby attribute. Since the navigations have visible headings, then aria-label is not the correct approach.  Since aria-labelledby uses a list of html IDs as its argument, you will need to add The implementation should be similar to as follows:

<nav aria-labelledby="dept-resources">
    <h2 id="dept-resources"> Department Resources</h2>
    ....
</nav>
<nav aria-labelledby="more-resources">
    <h2 id="more-resources">More Resources</h2>
    ...
</nav>

If any of the lists do not have a visible heading, then use aria-label with an appropriate description that would give a user a clue as to what links are contained in the region if they were choosing from a list of nav regions.

**Comment by bryanjonker-illinois** [comment]
Updated the example code
