### ISSUE TITLE
il-button class on anchor element hover

### ISSUE THREAD

**Issue by wrg20** [web-illinois/toolkit#328]
Adding the il-button class in the WYSIWYG editor to an anchor element <a> results in a text-decoration of underline on the button hover.  

![image](https://user-images.githubusercontent.com/1544079/159310456-35d1e532-d91e-4243-a9d3-65fe98096634.png)

![image](https://user-images.githubusercontent.com/1544079/159310394-bc816687-2246-4027-9049-327246266c12.png)

**Comment by bryanjonker-illinois** [comment]
Could not duplicate in the builder or the test pages. Checking https://drupal.webtheme.illinois.edu/, it looks like this is being caused by a drupal CSS (/sites/default/files/css/css_gOwl3MCCme8ACb6lKU-h0GPFQ4AWbEY0M31vKoRftt8.css)? 

![2022-03-31 13_35_36-DevTools - drupal webtheme illinois edu_](https://user-images.githubusercontent.com/65776851/161126119-1e7aca24-2a25-4eb5-88b9-599a31f8439e.png)
