### ISSUE TITLE
New component: Back to top

### ISSUE THREAD

**Issue by mattsharkey** [web-illinois/toolkit#61]
Model appearance, animation, and behavior on https://strategicplan.illinois.edu/.

* Not visible until scrolling
* Animates into view from the bottom and is fixed position
* Changes color when it is on top of the footer
* NEW: Add a white border so that it's visible when on top of same-colored page elements

**Comment by mwllr** [comment]
All the following are good: 
Model appearance, animation, and behavior on https://strategicplan.illinois.edu/.
Not visible until scrolling
Animates into view from the bottom and is fixed position
Changes color when it is on top of the footer
NEW: Add a white border so that it's visible when on top of same-colored page elements

Will want to change color when we get to the footer on next version.
Done for 2.1
