### ISSUE TITLE
Search slot action

### ISSUE THREAD

**Issue by melissawaller78** [web-illinois/toolkit#72]
How do we change the search slot action, i.e action="/search/node"?

Component has an empty "action" for search and we need that to be a specific link...

and the query name is currently "s" but we would like ours to be "query" because that's what google analytics looks for, otherwise we have to go change all of our analytics stuff
or Drupal need a way to bust into the component or not make the search piece a component at all...just give us a slot to put in our own component html or something.

**Comment by bryanjonker-illinois** [comment]
You can go into the "search" slot to insert your own component if that is needed. 

However, 
`<il-search slot="search" action="/search/node" method="get" searchname="query"></il-search> `
will get you what you want. I used "s" as the default because that is the WordPress default, and that's probably the userbase that is the most likely to need the defaults.

**Comment by bryanjonker-illinois** [comment]
https://cdn.brand.illinois.edu/toolkit/2.0/examples/components/header/multiple/index.html has this as an option now

**Comment by melissawaller78** [comment]
@wrg20 - can you check this??

**Comment by wrg20** [comment]
I was able to get the desired functionality I wanted with Bryan's comments above.  We just need to incorporate our ACES Google Custom Search module into the mix.  Thanks @bryanjonker-illinois !

**Comment by bryanjonker-illinois** [comment]
Closing per wrg20
